export const BRIDGE_BACKEND_ENV = "AGENT_BRIDGE_BACKEND";
export const BRIDGE_HOST_ENV = "AGENT_BRIDGE_HOST";
export const BRIDGE_SESSION_ID_ENV = "AGENT_BRIDGE_SESSION_ID";
export const LEGACY_SESSION_ID_ENV = "CODEX_COMPANION_SESSION_ID";
